#!/usr/bin/with-contenv bash

# copy config
[[ ! -e /config/user.ini ]] && \
	cp /defaults/user.ini /config/user.ini
cp /config/user.ini /etc/php7/conf.d/99-user.ini

# check for .env and copy default if needed
[[ ! -f "/config/www/.env" ]] && \
	cp /app/lychee/.env.example /config/www/.env

# create symlinks
symlinks=( \
/app/lychee/.env \
/app/lychee/storage/logs/laravel.log
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/"$(basename "$i")" "$i"
done

[[ ! -e "/config/www/uploads" ]] && mv /app/lychee/public/uploads /config/www/
rm -rf /app/lychee/public/uploads > /dev/null 2>&1
ln -s /config/www/uploads /app/lychee/public/uploads

# Create API key if needed
if [ ! -f "/config/LYCHEE_APP_KEY.txt" ];
	then
	echo "Generating Lychee app key for first run"
	key=$(php /app/lychee/artisan key:generate --show)
	echo $key > /config/LYCHEE_APP_KEY.txt
	echo "App Key set to $key you can modify the file to update /config/LYCHEE_APP_KEY.txt"
elif [ -f "/config/LYCHEE_APP_KEY.txt" ];
	then
	echo "App Key found - setting variable for seds"
	key=$(cat /config/LYCHEE_APP_KEY.txt)
fi

# .env file setup
# check to see if db_user is set, if it is then run seds and if not then leave them
if [ "${DB_USER}" ];
	then
	echo "Running config - db_user set"
	sed -i "s,APP_KEY=$,APP_KEY=${key},g" /config/www/.env
	sed -i "s/DB_HOST=127.0.0.1/DB_HOST=${DB_HOST}/g" /config/www/.env
	sed -i "s/DB_DATABASE=homestead/DB_DATABASE=${DB_DATABASE}/g" /config/www/.env
	sed -i "s/DB_USERNAME=homestead/DB_USERNAME=${DB_USER}/g" /config/www/.env
	sed -i "s/DB_PASSWORD=secret/DB_PASSWORD=${DB_PASS}/g" /config/www/.env
fi

# set appurl if detected
[[ "${APP_URL}" ]] && sed -i "s,#\sAPP_URL.*,APP_URL=${APP_URL},g" /config/www/.env

# update database - will set up database if fresh, or, migrate existing
php /app/lychee/artisan migrate

# disable CSRF for now since it prevents the API from being accessed programatically
sed -i "s/\s\\\\App\\\\Http\\\\Middleware\\\\VerifyCsrfToken/#\\\\App\\\\Http\\\\Middleware\\\\VerifyCsrfToken/g" /app/lychee/app/Http/Kernel.php

# permissions
chown -R abc:abc \
	/config \
	/app/lychee
